const fs = require('fs');
const path = require('path');
const { logger } = require('../utils/logger');

const nginxTemplateDir = path.join(__dirname, '../../nginx_templates');

exports.generateConfig = (subdomain, folderPath) => {
  const fullPath = `${process.env.WWW_ROOT}/${folderPath}`;

  const config = `# Nginx Configuration for ${subdomain}
# Auto-generated by XP Maestro Cloud

server {
    listen 80;
    listen [::]:80;
    
    server_name ${subdomain};
    
    root ${fullPath};
    index index.php index.html index.htm;
    
    # Redirect HTTP to HTTPS (enable when SSL is set up)
    # if ($scheme != "https") {
    #     return 301 https://$server_name$request_uri;
    # }
    
    # PHP-FPM Configuration
    location ~ \\.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Deny access to hidden files
    location ~ /\\. {
        deny all;
    }
    
    # Static files caching
    location ~* \\.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # Error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    
    access_log /var/log/nginx/${subdomain}.access.log;
    error_log /var/log/nginx/${subdomain}.error.log;
}`;

  return config;
};

exports.generateSSLConfig = (subdomain, folderPath, certPath, keyPath) => {
  const config = exports.generateConfig(subdomain, folderPath);
  
  // Add SSL configuration
  const sslConfig = `
# SSL Configuration
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name ${subdomain};
    
    ssl_certificate ${certPath};
    ssl_certificate_key ${keyPath};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
}`;

  return config + sslConfig;
};

exports.saveTemplateConfig = (subdomain, configContent) => {
  const templatePath = path.join(nginxTemplateDir, `${subdomain}.conf`);
  fs.writeFileSync(templatePath, configContent);
  logger.info(`Nginx template saved: ${templatePath}`);
};
